mutation updateArticle($input: UpdateArticleCommandInput!) {
    updateArticle(input: $input) {
      data {
        updatedAt
        title
        content
      }
      errors {
          code
          message
        }
    }
  }